

// component
import '@fortawesome/fontawesome-free/css/all.min.css';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark bg-white dark:bg-gray-800" suppressHydrationWarning={true}>
      <body
        className={`roboto-mono-regular antialiased bg-white dark:bg-gray-800`}
      >
        {children}
      </body>
    </html>
  );
}
