import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <nav>
            <ul className="flex gap-2 bg-gray-500 [&_li]:p-2 [&_li]:cursor-pointer ">
              <li ><Link href="/">Home</Link></li>
              <li ><Link href='/About'>About</Link></li>
              <li ><Link href='/Features'>Features</Link></li>
              <li ><Link href='/login'>Login</Link></li>
            </ul>
          </nav>
        </header>
          {children}
        <footer>
          <div className="bg-gray-500 p-2 absolute bottom-0">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus deserunt exercitationem unde suscipit aperiam eveniet adipisci neque delectus ex enim. Repellat aliquid optio tempora illum aspernatur. Dolorem quibusdam nostrum sequi!</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
